name: Symfony CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - preprod
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: composer install

      - name: Construire l'application
        run: php bin/console cache:clear --env=prod

      - name: Exécuter les tests
        run: php bin/phpunit

      - name: Configurer la base de données
        env:
          DB_NAME: app_db_dev  # Nom de la base de données pour la branche dev
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Déployer sur la branche dev
        if: github.ref == 'refs/heads/dev'
        run: |
          # Instructions spécifiques au déploiement sur la branche dev

      - name: Configurer la base de données
        env:
          DB_NAME: app_db_preprod  # Nom de la base de données pour la branche preprod
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Déployer sur la branche preprod
        if: github.ref == 'refs/heads/preprod'
        run: |
          # Instructions spécifiques au déploiement sur la branche preprod

      - name: Configurer la base de données
        env:
          DB_NAME: app_db_main  # Nom de la base de données pour la branche main
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Déployer sur la branche main
        if: github.ref == 'refs/heads/main'
        run: |
          # Instructions spécifiques au déploiement sur la branche main
