# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  symfony-init-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8'
    - name: Cache vendor folder
      uses: actions/cache@v3
      with:
        path: /vendor
        key: ${{ github.sha }}

    - name: Build vendor folder
      run: composer install
      # working-directory: /home/runner/work/devops-bookland_deployment/

  unitary-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve cached vendor folder
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ github.sha }}

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3

  changing-app-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: MySQL test
        run: mysql -h ${{ env.DATABASE_HOST }} -P ${{ env.DATABASE_PORT }} -u ${{ env.DATABASE_NAME }} -p ${{ env.DATABASE_PASSWORD }} -e "SELECT 1 + 1 AS solution"
        env:
          DATABASE_HOST: db-mysql-lon1-92536-do-user-14140355-0.b.db.ondigitalocean.com
          DATABASE_PORT: 25060
          DATABASE_NAME: doadmin
          DATABASE_PASSWORD: "AVNS_BbwjmXsjkS2rcDKqkkc"
        
