# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony PREPROD

on:
  push:
    branches: [ "preprod" ]
  pull_request:
    branches: [ "preprod" ]

permissions:
  contents: read

jobs:
  symfony-preprod-test:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8'

    - name: Install Symfony CLI
      run: |
        wget https://get.symfony.com/cli/installer -O - | bash
        export PATH="$HOME/.symfony/bin:$PATH"

    - name: Check Symfony requirements
      run: composer require --dev symfony/requirements-checker && vendor/bin/requirements-checker

  remove-debug-toolbar:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve cached vendor folder
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Disable Symfony debug toolbar
      run: | 
        export APP_ENV=prod

    # - name: Composer update
    #   run: composer update 
    #   working-directory: ${{ github.workspace }}
    
    - name: Build vendor folder
      run: composer install
      working-directory: ${{ github.workspace }}

    - name: PHPUnit tests
      run: vendor/bin/phpunit
